### ISSUE TITLE
[Feature Request] Simple finance tracking

### ISSUE THREAD

**Issue by mrghosti3** [Pool-Of-Tears/GreenStash#56]
### Checklist

- [X] This issue contains only one feature request. I will open one issue for every feature I want to request.
- [X] I checked, but didn't find any duplicates (open OR closed) of this issue in the repo.
- [ ] This feature is merely an UI/UX update.
- [X] This feature is not going to conflict with many of the existing features/options.

### Is your feature request related to a problem? Please describe.

I don't really have particular goals to save up money for, but there's not much options with fleshed out UI/UX like this app.

### Describe the solution you'd like

The ability to store simple transactions of payments that happened (or may happen later). The stored data:
1. recipient;
2. amount;
3. date: optional for if it's a payment that is upcoming, otherwise defaults to current date;
4. category: a tag/label that can be user created;
5. note: can be empty.

This could be a separate page in the menu.

### How will you/everyone benefit from this feature?

This would allow:
-  tracking finances, when you don't have any particular goals;
- filter transactions: by dates, by recipient or by category, one can check where you spend money;
- allow to see upcoming payments;
- have statistics of past transactions.

### Additional context

Do you accept Pull Requests so that maybe I could help/work on this feature in the app?

**Comment by starry-shivam** [comment]
Yep, I'm always open for PRs, i think maybe we can switch from sidebar navigation to bottom navigation and add this feature as a seperate tab in bottom navigation view, what do you think?

**Comment by mrghosti3** [comment]
Yeah that sounds like I had thought it could reached in the app. Though then it would be better to first implement issue #57

**Comment by starry-shivam** [comment]
Closing due to inactivity and since it's mostly out of scope for this project.

**Comment by mrghosti3** [comment]
Yeah, now that I thought about, it will be for the best if I'd rather try and make my own project for this type of app.
